name: SimpleApp

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - test-network
    links:
      - "backend:backend"

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    restart: on-failure
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
